[package]
name = "hazel"
version = "0.1.0"
authors = ["Danny McGee <dannymcgee@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "^0.12"
bitflags = "^1.2"
chrono = "^0.4"
crossbeam = "^0.8"
glfw = "^0.41"
